{"name": "Тест невозможности авторизации пользователя с неверными данными", "status": "passed", "description": "Создаем запись пользователя передавая email, пароль и имя. Затем входим с заведомо неверными логином и паролем.Должны получить в ответе код: 401 и значение 'success': False", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'my_email_y5963@gmail.com'"}, {"name": "password", "value": "'7219Pass.1'"}], "start": 1714943608748, "stop": 1714943609230}], "parameters": [{"name": "data_change", "value": "'password'"}], "start": 1714943608748, "stop": 1714943609232, "uuid": "26063445-8910-4dc5-892d-979f12d7882d", "historyId": "acad1282e40c596e80cc8c37265a3758", "testCaseId": "50a14353b09352770312ed64e2c88143", "fullName": "tests.test_user.TestUser#test_user_authorization_with_incorrect_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "DESKTOP-BIKQ56D"}, {"name": "thread", "value": "1764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}